spring:
  config:
    import: configserver:https://healthyeats-configserver-dev.herokuapp.com/
  application:
    name: healthyeats-userservice
  profiles:
    active: prod
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#server:
#  port: 8081
#      defaultZone: http://localhost:8070/eureka/